"""Importing this package registers every tool."""
from . import (  # noqa: F401
    apiscan,
    asm,
    cloud,
    deps,
    dns_email,
    dorks,
    injection_tools,
    network,
    ports,
    recon,
    secrets,
    sniper,
    sqli,
    ssl_scan,
    stored_xss,
    subdomains,
    takeover,
    typosquat,
    urlfuzzer,
    vhosts,
    webmisc,
    xss,
)
