"""Compliance mapping: turn findings into an OWASP/PCI-DSS/ASVS report pack."""
from __future__ import annotations

import json
from datetime import datetime, timezone
from html import escape

from webscan import __version__

# CWE -> (PCI-DSS requirement, OWASP ASVS section). Coarse but useful mapping.
CWE_MAP = {
    "CWE-79": ("6.5.7 Cross-site scripting", "V5.3 Output Encoding"),
    "CWE-89": ("6.5.1 Injection flaws", "V5.3 Injection Prevention"),
    "CWE-200": ("6.5.6 Information leakage", "V14.3 Information Disclosure"),
    "CWE-319": ("4.1 Encrypt transmission", "V9.1 Data in Transit"),
    "CWE-327": ("4.1 Strong cryptography", "V6.2 Algorithms"),
    "CWE-295": ("4.1 Trusted certificates", "V9.2 Server Communications"),
    "CWE-798": ("6.3.1 No hard-coded creds", "V2.10 Service Authentication"),
    "CWE-1104": ("6.3.3 Maintained components", "V14.2 Dependency"),
    "CWE-1021": ("6.5.x Clickjacking", "V14.4 HTTP Security Headers"),
    "CWE-16": ("2.2 Secure configuration", "V14.1 Build & Deploy"),
    "CWE-614": ("6.5.10 Session management", "V3.4 Cookie-based Session"),
    "CWE-1004": ("6.5.10 Session management", "V3.4 Cookie-based Session"),
    "CWE-601": ("6.5.x Redirects/forwards", "V5.1 Input Validation"),
    "CWE-942": ("1.3 Restrict access", "V14.5 HTTP Request Header Validation"),
}
SEV_ORDER = {"Critical": 0, "High": 1, "Medium": 2, "Low": 3, "Info": 4}


def render(scan_row: dict) -> str:
    data = json.loads(scan_row.get("json") or "{}")
    findings = sorted(data.get("findings", []), key=lambda f: SEV_ORDER.get(f.get("severity"), 9))
    rows = []
    for f in findings:
        cwes = f.get("classification", {}).get("cwe", []) or []
        pci = "; ".join(sorted({CWE_MAP[c][0] for c in cwes if c in CWE_MAP})) or "—"
        asvs = "; ".join(sorted({CWE_MAP[c][1] for c in cwes if c in CWE_MAP})) or "—"
        owasp = "; ".join(f.get("classification", {}).get("owasp_2021", [])) or "—"
        rows.append((f.get("severity", "Info"), f.get("title", ""),
                     ", ".join(cwes) or "—", owasp, pci, asvs))

    body = "\n".join(
        f'<tr><td><span class="sev-chip" style="--sev-color:var(--{sev.lower()});'
        f'--sev-bg:var(--{sev.lower()}-bg)">{escape(sev)}</span></td>'
        f"<td>{escape(title)}</td><td>{escape(cwe)}</td><td>{escape(owasp)}</td>"
        f"<td>{escape(pci)}</td><td>{escape(asvs)}</td></tr>"
        for sev, title, cwe, owasp, pci, asvs in rows) or \
        '<tr><td colspan="6">No findings to map.</td></tr>'

    from .html import _environment
    styles = _environment().get_template("_styles.html.j2").render()
    generated = datetime.now(timezone.utc).strftime("%b %d, %Y %H:%M UTC")
    return f"""<!DOCTYPE html><html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Compliance mapping — {escape(scan_row.get('target',''))}</title>{styles}</head>
<body><div class="sheet">
<header class="masthead"><span class="code">webscan</span>
<h1>Compliance Mapping</h1><span class="spacer"></span>
<span class="scan-type-pill">{escape(scan_row.get('tool_name',''))}</span>
<div class="sub">Target: {escape(scan_row.get('target',''))}</div></header>
<div class="notice">Findings mapped to OWASP Top 10 (2021), PCI-DSS v4 and OWASP ASVS.
This is an aid to compliance work, not a formal attestation.</div>
<h2 class="section">Control mapping</h2>
<div class="card" style="padding:6px"><div class="table-scroll" style="border:0">
<table class="data"><thead><tr><th>Severity</th><th>Finding</th><th>CWE</th>
<th>OWASP 2021</th><th>PCI-DSS v4</th><th>OWASP ASVS</th></tr></thead>
<tbody>{body}</tbody></table></div></div>
<footer><span>Generated by webscan-light v{__version__}</span><span>{generated}</span></footer>
</div></body></html>"""
